baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "https://bedecarroll.com" # the base hostname & protocol for your site
title: Bede Carroll
name: Bede Carroll
description: Admit nothing, deny everything and make counter-accusations
markdown: kramdown

author:
    name: "Bede Carroll"
    twitter: "bedecarroll"
    github: "bedecarroll"
    linkedin: "bedecarroll"

gems:
    - jekyll-mentions
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed

include:
    - ".well-known"

exclude:
    - "README.md"
    - "CHANGELOG.md"
    - "CNAME"
    - "Gemfile"
    - "Gemfile.lock"

permalink: :title
defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
