name: Bede Carroll
description: Admit nothing, deny everything and make counter-accusations

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://bedecarroll.github.io'
