baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://bedecarroll.com" # the base hostname & protocol for your site
title: Bede Carroll
description: Admit nothing, deny everything and make counter-accusations
# Fix highlighting as per http://stackoverflow.com/questions/16099153/table-not-render-when-use-redcarpet-in-jekyll-github-pages
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

author:
    name: "Bede Carroll"
    twitter: "bedecarroll"
    github: "bedecarroll"
    linkedin: "bedecarroll"

gems:
    - jekyll-mentions
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
exclude:
    - "README.md"
    - "CHANGELOG.md"
    - "CNAME"
    - "Gemfile"
    - "Gemfile.lock"
permalink: :title
defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
